### ISSUE TITLE
Re-add download as a context-specific command

### ISSUE THREAD

**Issue by peter-edge** [uber/prototool#144]
Right now, `download` uses whatever configuration is in your current directory, so for example if your current directory has no `prototool.yaml` file, and sub-directory `a/b` has `a/b/prototool.yaml` with `protoc_version: 3.4.0`, `prototool download` will download the default version of `protoc` (currently 3.5.1), not the version in the `prototool.yaml` file. We should make `download` and `clean` take `dirOrProtoFiles...` so `prototool download a/b` does what you expect.

**Comment by peter-edge** [comment]
Having thought about it overnight, I think we actually should not go to v1.0 with this, but quickly add it back in if there's someone who needs it. There's a lot of directions the "Prototool ecosystem" could go, and in the long-term, "download" may have no meaning.

**Comment by peter-edge** [comment]
@amckinney this was what I remember actually https://github.com/uber/prototool/issues/11 - idk I'm on the fence, thoughts @AlexAPB?

**Comment by AlexAPB** [comment]
Since we've moved to having exactly one `prototool.yaml` file and specify that it should always be at the root of your project, I don't think we really need to worry about this case. If someone is using prototool as intended, they should always get the right version of `protoc` downloaded.

Even if users run it in the wrong directory and download a wrong version, when we run a command that's using `protoc` (eg `compile`), we download the correct version first.

**Comment by peter-edge** [comment]
It's not about downloading the right version, it's about pre-downloading instead of your command waiting during runtime, which was brought up in #11.

**Comment by peter-edge** [comment]
I think we should close this for now, and re-add post-v1.0 if we need it.

**Comment by fgrosse** [comment]
Sorry for the late reply, I don't think it would be a super big issue if `download` was gone. However I still think it is useful in CI to have the protoc version already downloaded into the builder image rather than fetching it on each build job. The reason for this is that its nice if the builder image comes with batteries included and works even if we cannot fetch protoc for some reason ¯\_(ツ)_/¯. As @peter-edge pointed out in #11 already the speed improvements of this are probably negligible so this efficiency argument is only secondary to me here.

If there was no download command in prototool then I would probably download protoc myself and put it into the expected location. This sounds a bit like a hack though and not something you want to encourage users to do?

**Comment by peter-edge** [comment]
You can specify a location `HTTP GET` the protoc zip file from already with the `--protoc-url` flag. It probably wouldn't be too much work to make this more generic in terms of HTTP vs local file.

**Comment by peter-edge** [comment]
I put together #157 to allow local zip files to be used.
