### ISSUE TITLE
Automated GitHub Releases

### ISSUE THREAD

**Issue by abhinav** [uber/prototool#204]
The current release process involves building the binaries on a laptop and
uploading them to GitHub manually. We can automate this: Build the binaries in
CI and upload them directly to GitHub from there when a tag in the form
`vX.Y.Z` is pushed.

We do this already in yab. See yab's [.travis.yml][1] and [release.sh][2] for
inspiration. We should be able to continue using the releasegen.sh script and
adapt yab's extract_changelog script to prototool's changelog format.

There's some credentials-related setup involved. We should use one of our bot
credentials to cut the releases.

  [1]: https://github.com/yarpc/yab/blob/dev/.travis.yml
  [2]: https://github.com/yarpc/yab/blob/dev/scripts/release.sh

**Comment by peter-edge** [comment]
Would be nice - not sure it saves too much time or adds consistency (see below), but automation is generally good.

Note the build happens within a Docker container so that when there are panics, the location shows as `/go/src/...`. That should stay the same - Travis CI has Docker, so this shouldn't be too hard. Really the release process should remove the `vendor` directory and re-install as well, so that there's no chance of bad dependencies happening.

**Comment by peter-edge** [comment]
Closing this for now - working towards Inbox Zero, I don't think we're going to get to this, we can revisit if this becomes an issue later.
