### ISSUE TITLE
Generating JAR

### ISSUE THREAD

**Issue by VivekRagunathan** [uber/prototool#238]
Is there an option to generated a JAR directly from the proto files or out of the java files? 

The `protoc` has this option by suffixing the value for `--java_out` with `.jar`

**Comment by AlexAPB** [comment]
This won't work in today's world since `prototool` assumes that a given output path is a directory.
We'd need to add a flag/type/etc. to distinguish. Having this field would actually enable peter's suggestion in https://github.com/uber/prototool/issues/211#issuecomment-416765063.

Noting: https://developers.google.com/protocol-buffers/docs/reference/java-generated

Enabling this would be fairly low-priority for us, however. We may close this as wont-fix for the time being.
cc @amckinney

**Comment by peter-edge** [comment]
Following up - this may actually be something we want soon, thanks for pointing this out, I wasn't aware of this feature. I can't promise we're going to implement this but will get back to you soon.

**Comment by peter-edge** [comment]
See https://github.com/uber/prototool/pull/256

**Comment by peter-edge** [comment]
This is fixed on dev
