### ISSUE TITLE
Document remainder of new functionality for v1.4.0

### ISSUE THREAD

**Issue by jadekler** [uber/prototool#367]
Hiya. The README mentions:

> The breaking change detector may have additional checks added between minor versions, and therefore a change that might not have been breaking previously might become a breaking change.

However, I see no documentation about prototool exposing a breaking change detector. Is this some internal thing or am I able to use prototool to detect breaking changes?

**Comment by peter-edge** [comment]
Yea, it's on the `dev` branch, I just haven't documented it yet because I was potentially going to make more changes and didn't want anyone using it yet in OSS world. If you have Prototool installed from `dev`, type `prototool help break check` to see what is going on a bit.

I'll add documentation for it very soon as we're planning to release 1.4.0 soon, which means this feature will be stable (`dev` is unstable). I'll keep this issue open as a reminder for myself. Sorry about the confusion.

**Comment by jadekler** [comment]
Right on, thanks!

**Comment by peter-edge** [comment]
See https://github.com/uber/prototool/issues/131 for the initial discussion on the feature, this is what's implemented.

**Comment by peter-edge** [comment]
@jadekler note that v1.4.0 is our "biggest release yet", it's effectively v2.0.0 but without any breaking changes. See https://github.com/uber/prototool/blob/dev/CHANGELOG.md#unreleased for a short summary of the new features. I've just been procrastinating on documenting all of them, and also because we have been playing with the final feature set internally, and didn't want to do duplicate work.

**Comment by peter-edge** [comment]
Documentation is still in-progress, but see https://github.com/uber/prototool/pull/382 for a bit of an explanation of the workflow.

**Comment by YunLiaw** [comment]
I am curious about the docker image that will be provided in v1.4.0. Are you going to include python plugin inside of that image? I have looked at the Dockerfile in the dev branch, and it seems a no. Also any plan for supporting protocol buffer v3.7.0?

Thanks!

**Comment by peter-edge** [comment]
Python is included as a built-in for `protoc`, and the `grpc_python_plugin` is already included. You can use 3.7.0 right now, but haven't upgraded it inside the Docker image. Waiting for https://github.com/grpc/grpc/issues/18307 before installing `protoc` and the gRPC plugins from releases instead of Alpine `apk`, at which time the Docker image should be using the latest release of both (3.7.0 and 1.19.1).

**Comment by YunLiaw** [comment]
@peter-edge thanks for answering. I just tried to generate the python code from the `uber/prototool` docker container, and seems that it can generate python protocol buffer, but seems that it is not able to generate GRPC python codes.

Here is the generate block of my prototool.yaml:
```
generate:
  plugins:
    - name: python    # this one works
      output: gen/python
    - name: grpc_python  # this one does not work, but it is needed in order to generate the python grpc stubs
      output: gen/python
```

And here is the error message I got:
```
<input>:1:1:protoc-gen-grpc_python failed with status code 1.
<input>:1:1:protoc-gen-grpc_python not found or is not executable.
```

And when I go into `/usr/local/bin` of the container, grpc plugins for generate python stubs are not be able to be found.

I think python GRPC plugin is not included as a built-in. It needs to be manually built as stated in this comment: https://github.com/grpc/grpc/issues/7641#issuecomment-383310790. 

The following block is what I have tried to build GRPC plugins along with prototool:
```
ENV GRPC_VERSION=1.19.1
RUN \
    git clone -b ${GRPC_VERSION} https://github.com/grpc/grpc.git /tmp/grpc && \
    cd /tmp/grpc && \
    git submodule update --init && \
    make plugins -j12 && \
    cd /tmp/grpc/bins/opt && \
    ls | grep grpc_ | sed 'p;s/_plugin//;s/^/protoc-gen-/' | xargs -n2 mv && \
    mv /tmp/grpc/bins/opt/protoc-gen-* /usr/local/bin/
```
The full Dockerfile can be found [here](https://github.com/YunLiaw/prototool-python/blob/master/Dockerfile)

I would like to know if it can be added into the Dockerfile. But something needs to be noted is that compiling will fail on Alpine Linux 3.9 as reported in this issue: https://github.com/grpc/grpc/issues/18064, and some additional package will be needed in order to perform the compiling.

**Comment by peter-edge** [comment]
You need to use the `path` option for the plugin. See https://github.com/uber/prototool/blob/dev/etc/config/example/prototool.yaml#L159

This issue isn't meant to be for debugging unfortunately, this is meant to track the documentation updates. If you need further help, check out the `protoc` docs as this is more of a `protoc` issue, or we can talk in a different issue. Thanks!

**Comment by peter-edge** [comment]
@jadekler the breaking change detector is now documented at https://github.com/uber/prototool/blob/dev/docs/breaking.md but I'm keeping this issue open until I finish the remainder of the v1.4.0 documentation.

**Comment by peter-edge** [comment]
This is "done", will do a v1.4.0 release in a bit.

**Comment by YunLiaw** [comment]
Ah, I just found the plugin is under `/usr/bin` inside the container. Thanks!
