### ISSUE TITLE
Attach instance of AnyResolver to jsonpb.Marshaler for gRPC

### ISSUE THREAD

**Issue by huttarichard** [uber/prototool#415]
When I run for example something like `prototool grpc --address localhost:8080 --method "domain.v1.ServiceAPI/Method" --data '{.....}'` and rpc returns error, details are not parsed properly.

With `--debug` flag it says:
`ERROR	marshal error	{"error": "unknown message type \"domain.v1.ErrDetail\""}`. I checked the file, it is there has correct namespace, should be recognised. 

https://github.com/googleapis/googleapis/blob/master/google/rpc/status.proto#L93 is it because error details are type of Any?

Thanks.

**Comment by peter-edge** [comment]
This is going to be relatively difficult to solve and will take some work.

What is going on: https://godoc.org/github.com/golang/protobuf/jsonpb#Marshaler is what marshals Protobuf messages to JSON, and one of the fields is `AnyResolver`, which by default uses the message types registered with https://godoc.org/github.com/golang/protobuf/proto#RegisterType (for example, https://github.com/uber/prototool/blob/dev/example/gen/go/uber/foo/v1/foo.pb.go#L501), but these are only registered for code that is generated and linked into your Golang binary at compile time. Since types used with `prototool grpc` are not compiled into `prototool` (ie your individual Protobuf definitions are not compiled into the `prototool` binary, obviously), the default behavior for resolving `google.protobuf.Any` fails.

This can be fixed by attaching the return value for https://godoc.org/github.com/jhump/protoreflect/dynamic#AnyResolver to the `jsonpb.Marshaler` we create in `internal/grpc/invocation_event_handler.go` (and making the `jsonpbMarshaler` variable not a global since this `AnyResolver` will be different for each call to `prototool grpc`), but we need to interface with `github.com/jhump/protoreflect` properly to do this.

I'll mark this as a bug and look to fix it soon.

**Comment by peter-edge** [comment]
See #422.

**Comment by peter-edge** [comment]
This is done on dev and in the v1.6.0 release.
