### ISSUE TITLE
Not found proto file from include path when break check

### ISSUE THREAD

**Issue by sonatard** [uber/prototool#426]
prototool v 1.6.0

prototool generate is success but break check is failed.

```console
$ ls
admin/  api/  prototool.yaml

$ cat proto/prototool.yaml
protoc:
  version: 3.7.1
  includes:
    - ../../../../github.com/googleapis/googleapis
lint:
  group: uber2
  rules:
    remove:
     - NAMES_NO_DATA
     - ENUMS_HAVE_COMMENTS
     - ENUMS_HAVE_SENTENCE_COMMENTS
     - MESSAGES_HAVE_COMMENTS
     - MESSAGES_HAVE_COMMENTS_EXCEPT_REQUEST_RESPONSE_TYPES
     - MESSAGES_HAVE_SENTENCE_COMMENTS_EXCEPT_REQUEST_RESPONSE_TYPES
     - RPCS_HAVE_COMMENTS
     - RPCS_HAVE_SENTENCE_COMMENTS
     - SERVICES_HAVE_COMMENTS
     - SERVICES_HAVE_SENTENCE_COMMENTS
     - SERVICE_NAMES_API_SUFFIX
generate:
  go_options:
    import_path: github.com/sonatard/xxx/proto
  plugins:
    - name: go
      type: go
      flags: plugins=grpc
      output: ./go
    - name: gohttp
      type: go
      output: ./go

$ ls  proto/../../../../github.com/googleapis/googleapis
BUILD.bazel  CONTRIBUTING.md  LICENSE  Makefile  PACKAGES.md  README.md  WORKSPACE  gapic/  google/

$ prototool generate proto
$ ls proto/go
admin/  api/

$ prototool break check proto
2019-04-11T16:40:51.466+0900    WARN    protoc returned a line we do not understand, please file this as an issue at https://github.com/uber/prototool/issues/new       {"protocLine": "/var/folders/t7/github.com/googleapis/googleapis: warning: directory does not exist."}
2019-04-11T16:40:51.468+0900    WARN    protoc returned a line we do not understand, please file this as an issue at https://github.com/uber/prototool/issues/new       {"protocLine": "/var/folders/t7/github.com/googleapis/googleapis: warning: directory does not exist."}
<input>:1:1:/var/folders/t7/github.com/googleapis/googleapis: warning: directory does not exist.
<input>:1:1:/var/folders/t7/github.com/googleapis/googleapis: warning: directory does not exist.
<input>:1:1:Import "google/api/annotations.proto" was not found.
<input>:1:1:Import "google/api/annotations.proto" was not found.
```

**Comment by peter-edge** [comment]
Thanks for the detailed report here.

The issue is that you are including Protobuf files from outside your git repository, something I would not recommend. As explained in the [breaking change detector documentation's git section](https://github.com/uber/prototool/blob/dev/docs/breaking.md#git), how `prototool break check` works in git mode is to clone your repository to a temporary directory to compile the old versions of your Protobuf files. As such, relative imports outside of your git repository will not work.

I would not recommend including Protobuf files from a location on disk that is not inside your git repository - these Protobuf files will not be versioned correctly as your repository grows, and this is a non-hermetic build. If you are going to still do this, you can use the [breaking change detector's saved state workflow](https://github.com/uber/prototool/blob/dev/docs/breaking.md#saved-state) instead, which will not result in the above issue.

I will put up a PR to handle the protoc line above. Thanks again.

**Comment by jeffreyyong** [comment]
@bufdev hi I'm wondering if there's a better solution for importing a file that doesn't belong to my git repository?
```
import "google/api/http.proto";
```

This is what I have and I keep getting this error: `Import "google/api/http.proto" was not found or had errors.`
