### ISSUE TITLE
Feature Improvement Custom Lint Rule

### ISSUE THREAD

**Issue by seanliu1** [uber/prototool#454]
Are we able to load customized lint rules or defined customized lint rule in prototool.yml? 

for instance, I want something like enum with snake_case. 

Looks like everything is listed here https://github.com/uber/prototool/tree/dev/internal/lint, and we can only refer this list in prototool.yml

What is the policy of adding new lint (enum with snake_case) to the repo?

**Comment by jpreese** [comment]
This is something I was hoping for as well. Minimally expose the lint functionality in a more consumable package, so that others could write their own linting package that contains a fully configurable `yaml`. 

For example, maybe
```
{
  ...
  "serviceEndsWith": "your_text_here"
}
```

I love the `uber2` ruleset, but not so much ending services with API and having to name the `.proto` _api. But I DO want to enforce services ending in `Service`.

I would love to have more flexibility to define how exactly we want our `.proto` files to be laid out.

**Comment by smaye81** [comment]
This is a good idea, but outside the scope of prototool at the moment.  However, if you have a specific linter you want added we can add it into the codebase.  Please re-file a separate issue if so.
